### ISSUE TITLE
MongoDBException.php13mongo数据库连接授权失败:Authentication failed.[50] 

### ISSUE THREAD

**Issue by OhGui** [yumufeng/hyperf-mongodb#4]
$username = $this->config['username'];
            $password = $this->config['password'];
            if (!empty($username) && !empty($password)) {
                $uri = sprintf(
                    'mongodb://%s:%s@%s:%d/%s',
                    $username,
                    $password,
                    $this->config['host'],
                    $this->config['port'],
                    $this->config['db']
                );
            } else {
                $uri = sprintf(
                    'mongodb://%s:%d/%s',
                    $this->config['host'],
                    $this->config['port'],
                    $this->config['db']
                );
            }
            $urlOptions = [];
            //数据集
            $replica = isset($this->config['replica']) ? $this->config['replica'] : null;
            if ($replica) {
                $urlOptions['replicaSet'] = $replica;
            }
            $this->connection = new Manager($uri, $urlOptions);

     $Uri  拼接上db后会链接出错，如果配置文件里面的db 填了admin，  但要查询的数据库别的，这里就出问题了。
     同样的配置文件，在其它框架里面都可以。。。这里应该可以优化下

**Comment by yumufeng** [comment]
可以copy一份代码，然后提交上你改动后的
