### ISSUE TITLE
command方法没有兼容$skip（分页问题）

### ISSUE THREAD

**Issue by echo-LuGuang** [yumufeng/hyperf-mongodb#9]
因为一些复杂的分页条件（需要用到$in, $sort,$gte），fetchPagination并不满足我的条件。
我就用command方法操作。
问题：第一页没有问题 条件如下：
```json
[{"$sort":{"_id":-1}},{"$match":{"coupon_id":493,"user_id":{"$in":[1]}}},{"$limit":10},{"$skip":0}]
```
当我第二页的时候，无法返回数据
```json
[{"$sort":{"_id":-1}},{"$match":{"coupon_id":493,"user_id":{"$in":[1]}}},{"$limit":10},{"$skip":10}]
```

![image](https://github.com/yumufeng/hyperf-mongodb/assets/50095011/54e0bcca-a2ac-412e-b1b2-c89fdf8431db)

### 代码截图：

![image](https://github.com/yumufeng/hyperf-mongodb/assets/50095011/503a8f23-aac5-4c3a-ba62-a0c294fbd2bd)

**Comment by yumufeng** [comment]
可以使用下面方法，基于mongodb扩展的

$options = ['sort' => ['_id' => -1]]
$in = ['user_id' => [1,2,3]]
$where = [
            'coupon_id' => '',
            '$in' => $in
        ];
$page = 1
$pageSize = 20

$this->mongoDb->fetchPagination($this->collection, $pageSize, $page, $where, $options);

**Comment by echo-LuGuang** [comment]
> 可以使用下面的方法，基于mongodb的扩展
> 
> $options = ['sort' => ['_id' => -1]] $in = ['user_id' => [1,2,3]] $where = [ 'coupon_id' => '', '$在' => $在 ]; $页 = 1 $页大小 = 20
> 
> $this->mongoDb->fetchPagination($this->collection, $pageSize, $page, $where, $options);

![image](https://github.com/yumufeng/hyperf-mongodb/assets/50095011/8b63e4b9-b4f2-495c-bc18-0ea8cef901be)

![image](https://github.com/yumufeng/hyperf-mongodb/assets/50095011/d6e513ed-f512-4cb7-aa25-b202c42481a0)

不行老师，查出来的是空数组

**Comment by echo-LuGuang** [comment]
![image](https://github.com/yumufeng/hyperf-mongodb/assets/50095011/12798eb2-a7b9-4bc7-b1fa-abdcdf3a8617)

mongoDB类型没问题。头大

**Comment by yumufeng** [comment]
$in查询条件改一下 
`$inWhere = ['$in' => [1,2,3]]`

$options = ['sort' => ['_id' => -1]]
$where = [
            'coupon_id' => '',
            'user_id' => $inWhere
 ];
$page = 1
$pageSize = 20

$this->mongoDb->fetchPagination($this->collection, $pageSize, $page, $where, $options);


$in 或者$or 查询 命令传入到Where 里面进群

**Comment by echo-LuGuang** [comment]
> $in查询条件改一下 `$inWhere = ['$in' => [1,2,3]]`
> 
> $options = ['sort' => ['_id' => -1]] $where = [ 'coupon_id' => '', 'user_id' => $inWhere ]; $page = 1 $pageSize = 20
> 
> $this->mongoDb->fetchPagination($this->collection, $pageSize, $page, $where, $options);
> 
> $in 或者$or 查询 命令传入到Where 里面进群

![image](https://github.com/yumufeng/hyperf-mongodb/assets/50095011/062aa9ed-beec-43da-8d65-7d0f6ce5db9e)

我在option里传入了$in条件，正常了。 谢谢
